# Install REST Client for vscode to use
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

### GET
GET https://localhost:8080/api/person?limit=1&page=1

### GET BY ID
GET https://localhost:8080/api/person/62bb0b57034b86026f412e1b

### POST
POST https://localhost:8080/api/person
content-type: application/json

{
    "first_name": "John",
    "last_name": "Doe"
}
### PUT
PUT https://localhost:8080/api/person/62bafdda35b3ea029b1b706f
content-type: application/json

{
    "first_name": "Jane",
    "last_name": "Doe"
}
### DELETE
DELETE https://localhost:8080/api/person/62c2f9354ddf7a6dea8bca36