# Install REST Client for vscode to use
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

GET http://localhost:8080/api/person
###
POST http://localhost:8080/api/person
content-type: application/json

{
    "first_name": "John",
    "last_name": "Doe"
}
###
PUT http://localhost:8080/api/person/62babda93eb1089c845a6417
content-type: application/json

{
    "first_name": "Johnny",
    "last_name": "Cage"
}
###
DELETE http://localhost:8080/api/person/62bab749dc84e63e4ff817eb